import representative1 from "@/assets/representative-1.jpg";
import representative2 from "@/assets/representative-2.jpg";
import representative3 from "@/assets/representative-3.jpg";
import representative4 from "@/assets/representative-4.jpg";

export const fallbackNominees = [
  {
    id: "nominee-1",
    full_name: "Aissatou Mensah",
    country: "Ghana",
    profile_country: "Ghana",
    bio: "Youth civic educator focused on parliamentary literacy and digital participation for first-time voters.",
    avatar_url: representative1,
    title: "Civic Engagement Fellow",
    organisation: "Accra Youth Forum",
    vote_count: 182,
  },
  {
    id: "nominee-2",
    full_name: "Moussa Diallo",
    country: "Guinea",
    profile_country: "Guinea",
    bio: "Community organiser building regional youth dialogue across local assemblies and schools.",
    avatar_url: representative2,
    title: "Community Organiser",
    organisation: "Conakry Civic Lab",
    vote_count: 164,
  },
  {
    id: "nominee-3",
    full_name: "Nene Coker",
    country: "Sierra Leone",
    profile_country: "Sierra Leone",
    bio: "Policy volunteer advocating for youth employment and girls' leadership pipelines.",
    avatar_url: representative3,
    title: "Policy Volunteer",
    organisation: "Freetown Future Collective",
    vote_count: 149,
  },
  {
    id: "nominee-4",
    full_name: "Tijan Sarr",
    country: "Gambia",
    profile_country: "Gambia",
    bio: "Research assistant translating public priorities into legislative youth proposals.",
    avatar_url: representative4,
    title: "Research Assistant",
    organisation: "Banjul Policy Studio",
    vote_count: 133,
  },
];

export const fallbackRepresentatives = [
  {
    id: "rep-1",
    country: "Nigeria",
    full_name: "Zainab Okoli",
    short_bio: "Verified delegate representing youth-led entrepreneurship, civic ethics, and cross-border innovation policy.",
    manifesto_summary: "Advancing youth enterprise finance, parliamentary mentorship, and practical regional exchange.",
    headshot_url: representative1,
    avatar_url: representative1,
    title: "Verified Delegate",
    organisation: "Abuja Innovation Council",
    featured: true,
  },
  {
    id: "rep-2",
    country: "Benin",
    full_name: "Koffi Adje",
    short_bio: "Verified delegate working on trade mobility, local manufacturing, and youth participation in public hearings.",
    manifesto_summary: "Bringing SME access, civic monitoring, and youth committee reforms into the chamber.",
    headshot_url: representative2,
    avatar_url: representative2,
    title: "Verified Delegate",
    organisation: "Cotonou Trade Circle",
    featured: false,
  },
  {
    id: "rep-3",
    country: "Togo",
    full_name: "Ama Esi Kossi",
    short_bio: "Verified delegate focused on education access, women in leadership, and parliamentary outreach.",
    manifesto_summary: "Building stronger listening channels between young people, schools, and public institutions.",
    headshot_url: representative3,
    avatar_url: representative3,
    title: "Verified Delegate",
    organisation: "Lomé Youth Assembly",
    featured: true,
  },
  {
    id: "rep-4",
    country: "Liberia",
    full_name: "Joseph K. Toe",
    short_bio: "Verified delegate championing public service trust, conflict prevention, and skills-led legislation.",
    manifesto_summary: "Improving local policy awareness and linking youth networks with formal parliamentary process.",
    headshot_url: representative4,
    avatar_url: representative4,
    title: "Verified Delegate",
    organisation: "Monrovia Civic House",
    featured: false,
  },
];
